name: Custom build and install
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
    - uses: actions/checkout@v2
    - name: Install OpenCV
      uses: ./ # Uses an action in the root directory
      with:
        opencv-version: 4.0.0
        ENABLE_PRECOMPILED_HEADERS: OFF
        INSTALL_C_EXAMPLES: ON
        BUILD_EXAMPLES: ON
    - name: Check instalation
      run: |
        dpkg -l | grep libopencv
