name: Matrix testing
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test the action
    strategy:
      matrix:
        opencv: [ '3.4.10', '4.0.0', '4.3.0' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenCV ${{ matrix.opencv }}
        uses: ./ # Uses an action in the root directory
        with:
          opencv-version: ${{ matrix.opencv }}
      - name: Check instalation
        run: |
          dpkg -l | grep libopencv
